- /data/user/pfuerst/Reco_Analysis/Diffuse_sim_2012_nugen_11069_i3files/full/withDNN/01000-01999/
- /data/user/pfuerst/Reco_Analysis/Diffuse_sim_2012_nugen_11069_i3files/full/withDNN/02000-02999/
- /data/user/pfuerst/Reco_Analysis/Diffuse_sim_2012_nugen_11069_i3files/full/withDNN/03000-03999/
- /data/user/pfuerst/Reco_Analysis/Diffuse_sim_2012_nugen_11069_i3files/full/withDNN/04000-04999/
- /data/ana/Diffuse/IC2010-2014_NuMu/IC86-2012/datasets/finallevel/sim/2012/neutrino-generator/11070/wDNN/01000-01999/
- /data/ana/Diffuse/IC2010-2014_NuMu/IC86-2012/datasets/finallevel/sim/2012/neutrino-generator/11029/wDNN/02000-02999/
- /data/ana/Diffuse/IC2010-2014_NuMu/IC86-2012/datasets/finallevel/sim/2012/neutrino-generator/11029/wDNN/03000-03999/
- /data/ana/Diffuse/IC2010-2014_NuMu/IC86-2012/datasets/finallevel/sim/2012/neutrino-generator/11029/wDNN/04000-04999/
- /data/ana/Diffuse/IC2010-2014_NuMu/IC86-2012/datasets/finallevel/sim/2012/neutrino-generator/11029/wDNN/05000-05999/
